name: Report Bug 🪲
description: Report a bug to help us improve
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide as many details as possible to help us evaluate and resolve the bug report faster.

  - type: markdown
    attributes:
      value: |
        System Information

  - type: input
    id: os
    attributes:
      label: OS and version
      description: What operating system and version are you using?
      placeholder: OS
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: What happened? Please describe the bug in detail.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce Bug
      description: What steps can we follow to reproduce this bug?
      placeholder: 1. Step 1
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Result
    validations:
      required: true

  - type: input
    id: hash
    attributes:
      label: Commit hash
      description: Commit hash if known.
      placeholder: baf2aab0128f07262b564214ec70fc07befc6bb3

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any additional context or screenshots here.
