name: Feature Request 🔮
description: Suggest a new feature or improvement
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Share your idea with us! We'll carefully consider each suggestion for potential integration.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: If possible, provide example code or technical details for implementation.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
